[package]
name = "serde-enum-str-demo-no-std"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde-enum-str = { default-features = false, path = ".." }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
